<?php
/**
 * Created by PhpStorm.
 * User: Tom
 * Date: 11/18/2014
 * Time: 2:44 PM
 */

$form = $this->form;

$form->prepare();

?>
<div class="row">
    <div class="col-lg-12">
        <h1>Add User</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <?php echo $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('email')) ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('displayName')) ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('password')) ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('password2')) ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('role')) ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('submit')) ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>