<div class="row">
    <div class="col-lg-12">
        <a href="<?php echo $this->url('BeiUser\admin', array('action' => 'add')); ?>">Add User</a><br/><br/>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Users</h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Email</th>
                                <th>Display Name</th>
                                <th>State</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->users as $user): ?>
                                <tr>
                                    <td><?php echo $user['id']; ?></td>
                                    <td><?php echo $user['email']; ?></td>
                                    <td><?php echo $user['displayName']; ?></td>
                                    <td><?php echo $user['state']; ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('BeiUser\admin', array('action' => 'edit', 'id' => $user['id'])); ?>">Edit</a> |
                                        <a id="stateChangeLink" href="#">Disable</a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <?php echo $this->paginationControl($this->users, 'sliding', 'paginator.phtml'); ?>
            </div>
        </div>
    </div>
</div>